<a href="https://colab.research.google.com/github/vivekverma807/Data-Visualization/blob/main/Data_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("1D Array")
a = np.array([10,20,30,40])
print(a)

1D Array
[10 20 30 40]


In [ ]:
print("2D Array")
b = np.array([[10,20,30,40],[50,60,70,80]])
print(b)

2D Array
[[10 20 30 40]
 [50 60 70 80]]
