<a href="https://colab.research.google.com/github/vivekverma807/Data-Visualization/blob/main/Data_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("1D Array")
a = np.array([10,20,30,40])
print(a)

1D Array
[10 20 30 40]


In [ ]:
print("2D Array")
b = np.array([[10,20,30,40],[50,60,70,80]])
print(b)

2D Array
[[10 20 30 40]
 [50 60 70 80]]


In [2]:
import plotly.express as px
df1 = px.data.iris()
df1
fig1 = px.line(df1,
               x='sepal_length',
               y='petal_length',
               title='Sepal Length vs Petal Length',
               markers=True)
fig1.show()
fig2=px.box(df1,
            x='species',
            y='sepal_width',
            title = 'Sepal Length Distribution by Species')
fig2.show()

In [3]:
fig7 = px.line_3d(df1,
                  x='sepal_length',
                  y='sepal_width',
                  z='petal_length',
                  color='species',
                  title='3D Path of Iris Measurements')
fig7.show()

In [4]:
# 5D: X, Y, Z + Color (Petal Width) + Symbol (Species)
fig_symbol = px.scatter_3d(df1,
                           x='sepal_length',
                           y='sepal_width',
                           z='petal_length',
                           color='petal_width',
                           symbol='species',
                           title='5D Iris Analysis: Symbols & Color Scales')
fig_symbol.show()

In [5]:
from sklearn.decomposition import PCA

# Reduce the 4 iris features to 3 principal components
X = df1[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
pca = PCA(n_components=3)
components = pca.fit_transform(X)

# Create a new 3D plot with the results
fig_pca = px.scatter_3d(components, x=0, y=1, z=2,
                        color=df1['species'],
                        labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'},
                        title='PCA 3D Visualization: Maximize Variance')
fig_pca.show()

In [6]:
# Note: color requires numerical data, so we map species to a code
df1['species_id'] = df1['species'].astype('category').cat.codes

fig_para = px.parallel_coordinates(df1,
                                   color='species_id',
                                   labels={'species_id': 'Species'},
                                   color_continuous_scale=px.colors.diverging.Tealrose)
fig_para.show()

In [7]:
import plotly.graph_objects as go

# Creating a 3D Mesh plot for one species (e.g., Setosa)
setosa = df1[df1['species'] == 'setosa']

fig_mesh = go.Figure(data=[go.Mesh3d(x=setosa['sepal_length'],
                                    y=setosa['sepal_width'],
                                    z=setosa['petal_length'],
                                    opacity=0.5,
                                    color='cyan')])

fig_mesh.update_layout(title='3D Terrain Mesh: Setosa Cluster')
fig_mesh.show()

In [8]:
fig_anim = px.scatter_3d(df1,
                         x='sepal_length',
                         y='sepal_width',
                         z='petal_length',
                         color='species',
                         animation_frame='species',  # This creates the play button
                         title='Animated Species Reveal')

# Speed up the animation
fig_anim.layout.updatemenus[0].buttons[0].args[1]['frame']['duration'] = 1000
fig_anim.show()